language: python

python:
  - "2.7"

env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8


install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt

# command to run before tests
before_script:
- python manage.py Group
- python manage.py Badge
# command to run tests
script: python manage.py test
