#!/bin/bash

NAME="project"                                  # Name of the application
DJANGODIR=/home/univalle/trabajodegrado/services             # Django project directory
SOCKFILE=/home/univalle/trabajodegrado/services/run/gunicorn.sock  # we will communicte using this unix socket
USER=univalle                                        # the user to run as
GROUP=users                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=project.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=project.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
workon env
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ~/virtualenvs/env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=0.0.0.0:8001
  --log-level=debug \
  --log-file=-
